def ODEhelp():
    print('current models: \n - clifford_attractor \n - lorenz_system \n - damped_pendulum \n - rossler_attractor \n')
    print('to create a model: \n     model arguments should require initial conditions in x, y, and optionaly z dimensions; and constants.') 
    print('     use this format when creating custom models')
    print('\nexample 3D function with 3 constants: \ndef model_name(X, Y, Z, constants):')
    print('    RHO, SIGMA, BETA = constants')
    print('    dx = SIGMA * (Y - X)')
    print('    dy = X * (RHO - Z) - Y')
    print('    dz = X * Y - BETA * Z')
    print('    return [dx, dy, dz]')
    print('\nexample 2D function with 4 constants: \ndef model_name(X, Y, constants):')
    print('    A, B, C, D = constants')
    print('    dx = np.sin(A*Y) + C*np.cos(A*X)')
    print('    dy = np.sin(B*X) + D*np.cos(B*Y)')
    print('    return [dx, dy]')